services:
  mysql:
    image: mysql:8.0
    container_name: reformas_mysql
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reformas_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./procedures.sql:/docker-entrypoint-initdb.d/2-procedures.sql
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    container_name: reformas_backend
    ports:
      - "8083:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  frontend:
    image: nginx:alpine
    container_name: reformas_frontend
    ports:
      - "3002:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: reformas_phpmyadmin
    ports:
      - "8084:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
